# generated by opal/pymake (release 0.3/98-05-10)

all: sgmlop.dll

sgmlop.obj: sgmlop.c
	cl -nologo -c -W3 -O2 -MD -DWIN32 -DNDEBUG -Ic:\pythonware\src\python-1.5\include -Ic:\pythonware\src\python-1.5\pc sgmlop.c

sgmlop.dll: sgmlop.obj
	link -nologo -dll -machine:ix86 sgmlop.obj c:\pythonware\src\python-1.5\pcbuild\release\python15.lib kernel32.lib user32.lib gdi32.lib

