#!/usr/bin/python

from xml.dom.html_builder import HtmlBuilder
from xml.dom.writer import HtmlWriter
import sys

b = HtmlBuilder()
b.feed(open(sys.argv[1]).read())

w = HtmlWriter()
w.write(b.document)

